### ISSUE TITLE
Not compatible with Ember 2.5beta

### ISSUE THREAD

**Issue by Gaurav0** [mike-north/ember-load#12]
Ember 2.5beta no longer supports ember-legacy-views

**Comment by lolmaus** [comment]
Say whaaaat! My styling strategy heavily relies on `ember-legacy-views` -- how can I otherwise apply classes to all those HTML elements generated by what used to be Ember views?

**Comment by mixonic** [comment]
Ember 2.5 should still support ember-legacy-views, though support is deprecated in Ember 2.4. Ember 2.6 (currently canary) is the first version of Ember to not support legacy views.

Ember 2.4 is an LTS, and will be supported until late October when its lifecycle will end in favor of Ember 2.8 LTS. Core is definitely away of the routed-template-root-element issue, and would like to have a solution in place for 2.8 to ensure a smooth transition for those who need that feature.

**Comment by Gaurav0** [comment]
@mixonic Shall I correct the information here: https://github.com/emberjs/ember-legacy-views/blob/master/README.md ?

**Comment by nanuxbe** [comment]
I'm not sure I understand what's blocking this issue after https://github.com/mike-north/ember-load/commit/501755246e6f74e1aef646889d658d90d39c3dd1 has been merged?

**Comment by Gaurav0** [comment]
@nanuxbe Agreed. No longer using ember-legacy-views.
