### ISSUE TITLE
Currently broken on IE11

### ISSUE THREAD

**Issue by john-griffin** [mike-north/ember-load#134]
`0.0.13` and up breaks apps when running in IE11. Errors are occurring around  the `forEach` introduced recently https://github.com/mike-north/ember-load/blame/1d656b17e75f1ad8f10c060cd12e825599c02f09/addon/components/ember-load-remover.js#L23 which is making it into the final build when targeting IE11.

**Comment by corrspt** [comment]
Also bit by this, since the issue was closed, didn't found it at first (since there's no release with this)

**Comment by mike-north** [comment]
The version I just ( 0.0.15 ) cut should contain a fix (#135)

**Comment by repl-shenoy-sukumaran** [comment]
Still broken in 0.0.15. I could see potential fix commit https://github.com/mike-north/ember-load/commit/ce59f475ae949ab109e1efff3928d8492c5fb5ad 
But this is not part of 0.0.15. will be cutting new release?

**Comment by mike-north** [comment]
This means that the fix was ineffective. [These](https://github.com/mike-north/ember-load/compare/v0.0.15...master) are the only commits to master since 0.0.15 (just dependency upgrades)
