### ISSUE TITLE
Get add-on working with Ember 2.0

### ISSUE THREAD

**Issue by acorncom** [mike-north/ember-load#2]
Looks like this add-on doesn't support Ember 2.0 without the use of the ember-legacy-views add-on.  Do you have any pointers on how we might get that working?  I'd be happy to help with the work, but am not quite sure where to start ... :-)

**Comment by jandillmann** [comment]
Maybe this can be solved with CSS only. Ember adds the `ember-application` class to the body when it's ready, so hiding the loading div once this class has been added to `body` should do the trick.

    .ember-application .ember-load-indicator {
      display: none;
    }

**Comment by mike-north** [comment]
As you guys probably know, Ember 2.0 still uses views under the hood. I'm going to wait for routable components until I advise an "ember 2.0" path other than `ember-legacy-views`

**Comment by acorncom** [comment]
> I'm going to wait for routable components until I advise an "ember 2.0" path other than ember-legacy-views

Sounds good.  Thought that was probably the case :-)

**Comment by acorncom** [comment]
@jandillmann Appreciate the input, that does everything I needed on my end. :+1:

**Comment by mike-north** [comment]
We now have a setup blueprint that will install `ember-legacy-views` into consuming apps automatically - #4. Anyone following the `ember install ember-load` installation method should have no view-related ember 2.0 problems

**Comment by acorncom** [comment]
:+1: @mike-north just curious, but what would you say the advantage would be to using this add-on vs a straight CSS solution as mentioned above?

**Comment by mike-north** [comment]
There isn't much to this addon. It just yanks your loader out at an appropriate time
