### ISSUE TITLE
Release the update

### ISSUE THREAD

**Issue by lolmaus** [mike-north/ember-load#6]
Don't forget a git tag! ^_^

A changelog would be awesome.

**Comment by knownasilya** [comment]
Yes, after you merge my PR :+1: 

Great idea by the way!

**Comment by lolmaus** [comment]
@knownasilya We need this well-maintained. Would you like to own a fork?

**Comment by knownasilya** [comment]
@mike-north could you add me as a maintainer? Otherwise a fork might be in order.. :cry:

**Comment by knownasilya** [comment]
Thank you @mike-north!
