### ISSUE TITLE
Configurable ember-load-remover

### ISSUE THREAD

**Issue by nagits** [mike-north/ember-load#64]
Please, move ```$(`.${loadingIndicatorClass}`).remove();``` outside of didInsertElement (into `removeLoader()` maybe).

For example, if i want to fadeOut the element instead of just deleting, i will be able to simply override `removeLoader`:
```js
// app/components/ember-load-remover.js
import EmberLoadRemover from 'ember-load/components/ember-load-remover';
export default EmberLoadRemover.extend({
  removeLoader(loadingIndicatorClass) {
    $(`.${loadingIndicatorClass}`).fadeOut(300, function() {
      $(this).remove();
    });
  }
}
```

For now, it isn't very good to override didInsertElement due to addon-specific code in this function.

**Comment by mike-north** [comment]
I like the idea behind this. didInsert is handy because it doesn't get
invoked on fastboot, but let me see if I can propose something that will
make your use case work

**Comment by sheriffderek** [comment]
So, is this 0.0.11 and up? I was using 0.0.7 and it didn't seem to work, but 0.0.11 does. (I could have been doing something wrong) but if this ability is a particular version and up, consider adding a note in the readme.
