### ISSUE TITLE
url doesn't work

### ISSUE THREAD

**Issue by ibroadfo** [mike-north/ember-load#73]
should be http://mike-north.github.io/ember-load/
![screen shot 2017-01-08 at 15 59 48](https://cloud.githubusercontent.com/assets/1550/21751278/a02b35de-d5bc-11e6-951b-c1c78236b068.png)

**Comment by sheriffderek** [comment]
Hmmm I thought this may be a duplicate of #68 - but it's not.

**Comment by mike-north** [comment]
New URL is [mike.works/oss/ember-load](https://mike.works/oss/ember-load)
