### ISSUE TITLE
DEPRECATION: The `initialize` method for Application initializer 'hide-loading-screen' should take only one argument - `App`, an instance of an `Application`.

### ISSUE THREAD

**Issue by lolmaus** [mike-north/ember-load#9]
> DEPRECATION: The `initialize` method for Application initializer 'hide-loading-screen' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.

**Comment by mike-north** [comment]
What version are you using? Initializers in this addon currently have an arity of 0

**Comment by mike-north** [comment]
I suspect that this is from an old version or something, because [this treats deprecations as errors in CI](https://github.com/mike-north/ember-load/blob/master/tests/dummy/config/environment.js#L35). Please re-open if you feel that this is in error

**Comment by mike-north** [comment]
#5
